# -*- coding: utf-8 -*-
"""SMSSpamNLPDL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aM8ngnwL373tau_XiAbUi6dBnuUuoKYX
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
import re
import nltk
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer

email_datas = pd.read_csv('/content/spamraw.csv')

email_datas

LE = LabelEncoder()
email_datas['type'] = LE.fit_transform(email_datas['type'])

email_datas

nltk.download('stopwords')
from nltk.corpus import stopwords

def clean_text(text):
  text = text.lower()
  text = re.sub(r'[^a-z]', ' ', text)
  words = text.split()
  words = [ word for word in words if word not in stopwords.words('english')]
  return " ".join(words)
email_datas['cleaned_text'] = email_datas['text'].apply(clean_text)

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(email_datas['cleaned_text'])
Y = email_datas['type']

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

model = LogisticRegression()
model.fit(X_train,Y_train)

Y_pred = model.predict(X_test)
print("Model Accuracy:", accuracy_score(Y_test,Y_pred))

example =["Shall call now dear having food"]
example_clean =[clean_text(text) for text in example]
example_vec = vectorizer.transform(example_clean)

prediction = model.predict(example_vec)
if prediction == 1:
  print("Spam")
else:
  print("Ham")

